---

- name: Configuring kubelet to work fine
  hosts: all
  become: yes
  tasks: 

    - name: ADD Configuration to docker daemon file
      shell: |
        cat > /etc/docker/daemon.json <<EOF
        {
          "exec-opts": ["native.cgroupdriver=systemd"],
          "log-driver": "json-file",
          "log-opts": {
            "max-size": "100m"
          },
          "storage-driver": "overlay2",
          "storage-opts": [
            "overlay2.override_kernel_check=true"
          ]
        }
        EOF

    - name: Create docker service file
      file:
        path: /etc/systemd/system/docker.service.d
        state: directory

    - name: restart service cron on centos, in all cases, also issue daemon-reload to pick up config changes
      systemd:
        state: restarted
        daemon_reload: yes
        name: docker
