---

- name: Setting up and installing docker
  hosts: all
  become: true
  #vars: 
  # containerd:
  #   - overlay
  #     br_netfilter
  # kubernetescri:
  #   - net.bridge.bridge-nf-call-iptables = 1
  #     net.ipv4.ip_forward = 1
  #      net.bridge.bridge-nf-call-ip6tables = 1

  tasks:
    
    - name: Load required kernel modules to containerd.conf
      shell: |
        cat << EOF | sudo tee /etc/modules-load.d/containerd.conf
        overlay
        br_netfilter
        EOF

    - name: Modprobe modules
      shell: |
        modprobe overlay
        modprobe br_netfilter

    - name: Modifying system settings for k8s
      shell: |
        cat <<EOF | sudo tee /etc/sysctl.d/99-kubernetes-cri.conf
        net.bridge.bridge-nf-call-iptables  = 1
        net.ipv4.ip_forward                 = 1
        net.bridge.bridge-nf-call-ip6tables = 1
        EOF    
        sysctl --system
